Repository VibrentHealth/pipelinewise, pull requests merged in 2025-03, with the labels that each got.

#2 feat(snowflake-connector): updating snowflake-connector version for target-snowflake
  singer-connectors/target-snowflake/setup.py
Labels: ready for review, size/XS

#4 feat(pipelinewise-singer-python): updating pipelinewise-singer-python version for target-snowflake
  singer-connectors/target-snowflake/setup.py
Labels: ready for review, size/XS

#6 feat(pipelinewise-ssl-tapmysql): updating tapmsql, removed ssl
  singer-connectors/tap-mysql/tap_mysql/connection.py
Labels: size/XS

#7 fix(workflow): updated the ubuntu image to prevent brownout
  .github/workflows/connectors.yml
  .github/workflows/e2e_tests.yml
  .github/workflows/lint_unit_tests.yml
Labels: size/S
